version: '3.8'

services: 
  neo4j:
    image: neo4j:4.4
    env_file: ./.env
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    networks:
      - backend-network

  opensearch:
    image: opensearchproject/opensearch:1.3.3
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      nofile:
        soft: 1024
        hard: 2048
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./opensearch/data:/usr/share/opensearch/data

networks:
  backend-network: {}

volumes:
  neo4j_data: {}
  opensearch_data: {}
